FROM centos:centos6
MAINTAINER A D Ministator email: peteja@vsp.com, edha@vsp.com

# Update the image with the latest packages (recommended)
RUN yum update -y; yum clean all

# Add wget 
RUN yum install wget -y
RUN yum install tar -y

