FROM innovate_base 
 
MAINTAINER A D Ministator email: peteja@vsp.com

# Update the image with the latest packages (recommended)
RUN yum update -y; yum clean all

# Install Java

RUN yum install java-1.7.0-openjdk -y
