FROM innovate_java
MAINTAINER A D Ministator email: peteja@vsp.com, edha@vsp.com

# Update the image with the latest packages (recommended)
RUN yum update -y; yum clean all

# Add wget 
RUN yum install wget -y

# Get the tomcat binaries


# Unpack the tomcat binaries


# Docker automatically extracted. So move files to web directory
# RUN mv /tmp/mysite/* /var/www/html

EXPOSE 8080

# ENTRYPOINT /bin/bash
